print('Hello, world...')
print("*************")
str = 'hello world'
print(str)
print("*************")
print("print('hellooooo.')")
print("*************")
print('Hello, world1\nHello, world2\nHello, world3')
print("*************")
print('Hello'+'world')
print('Hello'+' world')
print('Hello'+' '+'world')